name: CalVer Creation
description: Automatically create a new CalVer following YYYY.MM.DD

inputs:
  timezone:
    description: 'The time zone to base the date on, e.g. UTC, America/Chicago, etc. (default: UTC)'
    required: false
    default: 'UTC'
  push_tag:
    description: 'If the newly created version tag should be pushed (default: false)'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub token for pushing tags'
    required: false
outputs:
  new_version:
    description: 'The newly generated version tag'

runs:
  using: composite
  steps:
    - name: Checkout calling repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        # TODO: Use the .python-version file contents
        python-version: '3.13'
    
    - name: Install Python dependencies
      shell: bash
      # TODO: setup output grouping
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Pre Check
      env:
        INPUT_TIMEZONE: ${{ inputs.timezone }}
        INPUT_PUSH_TAG: ${{ inputs.push_tag }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: python ${{ github.action_path }}/pre_check.py

    - name: Generate new tag
      id: new_tag
      env:
        INPUT_TIMEZONE: ${{ inputs.timezone }}
      shell: bash
      run: python ${{ github.action_path }}/generate_new_tag.py